version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: postgres:latest
    container_name: pg
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "25432:5432"